-- nats.x
-- NATS messaging module for Tzopilotl.
-- Foreign functions are registered by the bridge; this module provides
-- any enum/constant definitions needed by the NATS subsystem.
--
-- Currently no enums are needed. The foreign functions registered under
-- the "nats" module namespace are accessible via: import nats.*;
