-- notebook.x -- programmatic construction of .tzd notebook documents.
--
-- Builds the app's notebook container format from code, so notebooks can
-- be generated by scripts instead of only by GUI editing. A .tzd file is
-- exactly a TZB-encoded Msg tree (std.messageEncoding, documented in
-- FFI_Guide.html section 15); the record layout here mirrors the app's
-- canonical writer (app/src/document.cpp, content_hash.cpp):
--
--   (doc 2 nextCellId (cells cell...) (panels))
--   cell = (cell id kindInt name text runOnLoad panelHeight collapsed (presets))
--
-- Cell kinds: 0 prose, 1 code, 2 panel, 3 presets.
--
-- Only the stable current-state sections are written. No widget records:
-- ui constructors are idempotent upserts keyed by (panel, name), so a
-- run-on-load code cell recreates its widgets when the document opens.
-- No history section: the file opens with a fresh undo tree, like any
-- document saved by a pre-v2 build.

import std.message.*;
import std.messageEncoding.*;

-- One notebook cell, pre-serialization. Usually built with the
-- constructors below rather than directly.
struct NotebookCell {
    kind Int,
    name String,
    text String,
    runOnLoad Bool,
    panelHeight Float,
    collapsed Bool,
}

-- A prose (text) cell.
fn proseCell(text String) NotebookCell =
    NotebookCell { kind: 0, name: "", text: text, runOnLoad: false,
                   panelHeight: 240.0, collapsed: false };

-- A code cell. `name` is the optional label shown in the cell header.
fn codeCell(text String, runOnLoad Bool = false, name String = "") NotebookCell =
    NotebookCell { kind: 1, name: name, text: text, runOnLoad: runOnLoad,
                   panelHeight: 240.0, collapsed: false };

-- A panel cell claiming widget panel `name` (and its "name/sub" tabs).
-- Widgets appear when the code that creates them runs.
fn panelCell(name String, height Float = 240.0) NotebookCell =
    NotebookCell { kind: 2, name: name, text: "", runOnLoad: false,
                   panelHeight: height, collapsed: false };

-- An empty presets cell; slots are captured from the GUI.
fn presetsCell(name String = "") NotebookCell =
    NotebookCell { kind: 3, name: name, text: "", runOnLoad: false,
                   panelHeight: 240.0, collapsed: false };

fn _sym(s String) Msg = Msg.symbol(toSymbol(s));

fn _cellMsg(id Int, c NotebookCell) Msg =
    Msg.vec([_sym("cell"), Msg.int(id), Msg.int(c.kind),
             Msg.string(c.name), Msg.string(c.text), Msg.bool(c.runOnLoad),
             Msg.float(c.panelHeight), Msg.bool(c.collapsed),
             Msg.vec([_sym("presets")])]);

-- The document as a Msg tree, cells numbered 1..n in order.
fn notebookMsg(cells [NotebookCell]) Msg {
    var recs = [_sym("cells")];
    var id = 1;
    for (c : cells) {
        recs push!(_cellMsg(id, c));
        id = id + 1;
    }
    Msg.vec([_sym("doc"), Msg.int(2), Msg.int(id), Msg.vec(recs),
             Msg.vec([_sym("panels")])])
}

-- The document as .tzd file bytes.
fn notebookBytes(cells [NotebookCell]) Bytes = cells notebookMsg encode;

-- Write the notebook to `path` (conventionally ending in ".tzd").
-- Returns false if the file cannot be written.
fn saveNotebook(path String, cells [NotebookCell]) Bool =
    writeFile(path, cells notebookBytes);
